run:
  timeout: 10m
  modules-download-mode: vendor
  build-tags:

linters:
  enable:
    - gofmt
    - govet
    - deadcode
    - goimports
    - ineffassign
    - misspell
    - unused
    - varcheck
    - golint
    - staticcheck
    - typecheck
    - structcheck
  disable-all: true

issues:
  exclude-rules:
    - linters:
        - golint
      text: "stutters"
